/**
 * AUTO-GENERATED STUB - DO NOT EDIT MANUALLY
 * Generated by scripts/auto-fix-imports.js
 * TODO: Replace with actual implementation
 */

// Export stub types
export type PreviewTestingManager = any;
export type PreviewTestingManagerConfig = any;
export type PreviewTestingManagerOptions = any;

// Export stub objects/functions
export const previewtestingmanager = {} as any;
export const createPreviewTestingManager = () => ({} as any);
export const getPreviewTestingManager = () => ({} as any);

// Export default
const stub = {
  previewtestingmanager,
  createPreviewTestingManager,
  getPreviewTestingManager,
};

export default stub;
