/**
 * AUTO-GENERATED STUB - DO NOT EDIT MANUALLY
 * Generated by scripts/auto-fix-imports.js
 * TODO: Replace with actual implementation
 */

// Export stub types
export type Types = any;
export type TypesConfig = any;
export type TypesOptions = any;

// Export stub objects/functions
export const types = {} as any;
export const createTypes = () => ({} as any);
export const getTypes = () => ({} as any);

// Export default
const stub = {
  types,
  createTypes,
  getTypes,
};

export default stub;
