/**
 * Application Configuration - Generated by DCT CLI
 * Created: 2025-09-25T18:31:22.504Z
 * Preset: universal-consultation
 * Tier: advanced
 */

// Override environment-based configuration with CLI-generated values
process.env.APP_TIER = 'advanced';
process.env.APP_PRESET = 'universal-consultation';
process.env.APP_NAME = 'Final Test Company';

// Import the main configuration
import config from './app.config.base';

// Export the configuration with CLI overrides
export * from './app.config.base';
export default config;
