/**
 * Application Configuration - Generated by DCT CLI
 * Created: 2025-08-29T16:35:31.828Z
 * Preset: realtor-listing-hub
 * Tier: pro
 */

// Override environment-based configuration with CLI-generated values
process.env.APP_TIER = 'pro';
process.env.APP_PRESET = 'realtor-listing-hub';
process.env.APP_NAME = 'Premier Realty';

// Import the main configuration
import config from './app.config.base';

// Export the configuration with CLI overrides
export * from './app.config.base';
export default config;
