/**
 * AUTO-GENERATED STUB - DO NOT EDIT MANUALLY
 * Generated by scripts/auto-fix-imports.js
 * TODO: Replace with actual implementation
 */

// Export stub types
export type Deployment = any;
export type DeploymentConfig = any;
export type DeploymentOptions = any;

// Export stub objects/functions
export const deployment = {} as any;
export const createDeployment = () => ({} as any);
export const getDeployment = () => ({} as any);

// Export default
const stub = {
  deployment,
  createDeployment,
  getDeployment,
};

export default stub;
