/**
 * AUTO-GENERATED STUB - DO NOT EDIT MANUALLY
 * Generated by scripts/auto-fix-imports.js
 * TODO: Replace with actual implementation
 */

// Export stub types
export type TemplateManifest.schema = any;
export type TemplateManifest.schemaConfig = any;
export type TemplateManifest.schemaOptions = any;

// Export stub objects/functions
export const templatemanifest.schema = {} as any;
export const createTemplateManifest.schema = () => ({} as any);
export const getTemplateManifest.schema = () => ({} as any);

// Export default
const stub = {
  templatemanifest.schema,
  createTemplateManifest.schema,
  getTemplateManifest.schema,
};

export default stub;
