/**
 * AUTO-GENERATED STUB - DO NOT EDIT MANUALLY
 * Generated by scripts/auto-fix-imports.js
 * TODO: Replace with actual implementation
 */

// Export stub types
export type CompatibilityChecker = any;
export type CompatibilityCheckerConfig = any;
export type CompatibilityCheckerOptions = any;

// Export stub objects/functions
export const compatibilitychecker = {} as any;
export const createCompatibilityChecker = () => ({} as any);
export const getCompatibilityChecker = () => ({} as any);

// Export default
const stub = {
  compatibilitychecker,
  createCompatibilityChecker,
  getCompatibilityChecker,
};

export default stub;
