name: feat/route-adapter-guard

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  route-adapter-guard:
    uses: dontaedct/ch-git/.github/workflows/route-adapter-guard-core.yml@main
    with:
      base_sha: ${{ github.event.pull_request.base.sha || '' }}
      head_sha: ${{ github.event.pull_request.head.sha || '' }}
    secrets: inherit
